# Generated by Django 4.2.5 on 2024-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lucify', '0003_aboutfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
